//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace employeeCardCreate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string NationalId { get; set; }
        public string NationalCode { get; set; }
        public string PassportId { get; set; }
        public string Region { get; set; }
        public string JobSituation { get; set; }
        public string LetterId { get; set; }
        public string AnalArea { get; set; }
        public string FirstArea { get; set; }
        public string SecondArea { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public Nullable<int> SecondaryCard { get; set; }
        public Nullable<System.DateTime> DateSecondaryCard { get; set; }
        public string LostCard { get; set; }
        public string TypeLostCard { get; set; }
        public Nullable<System.DateTime> FindLostCardDate { get; set; }
        public byte[] Image { get; set; }
        public string CompanyName { get; set; }
        public string CompanyResName { get; set; }
        public string CompanyNum { get; set; }
        public string ContractorName { get; set; }
        public string ContractorResName { get; set; }
        public string ContarctorNum { get; set; }
        public Nullable<int> Print { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<int> @is { get; set; }
        public Nullable<System.DateTime> LostCardDate { get; set; }
        public string user { get; set; }
    }
}
